### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by greensopinion** [greensopinion/flutter-vector-map-tiles#1]
memory usage grows unreasonably as the map is zoomed/panned, especially in dense areas such as London

**Comment by ibrierley** [comment]
I guess maybe one question is whether it's a leak, or just large data which needs culling if out of sight and it gets above a certain level ? In the past I just did it time based, but maybe an option where an app can specify an ideal limit to stay under ? (never sure if thats a good thing or not).

**Comment by greensopinion** [comment]
fixed in https://github.com/greensopinion/dart-vector-tile-renderer/commit/d9a285969027c450d221a28f7b31b22187463877
