### ISSUE TITLE
Converting Json into an Theme

### ISSUE THREAD

**Issue by KerimYilPROCON** [greensopinion/flutter-vector-map-tiles#103]
I'm currently trying to use widget inside an project of mine but I'm facing an issue when trying to convert an Json into a Theme.

I've looked at the example and saw that there was an theme reader but it isn't referenced inside the libary which is why you can't use it. And while trying to convert in on my own I have noticed that the class Theme needded for the widget is an self made theme class and not the standard one (which isn't referenced as well). Aynone got any tips on how to convert into an proper theme?

[The Theme](https://maps.wien.gv.at/basemapv/bmapvhl/3857/resources/styles/root.json)

**Comment by geisterfurz007** [comment]
Something a little like this:

```dart
import 'package:vector_tile_renderer/vector_tile_renderer.dart';

final /* or const */ myTheme = {/* your theme, or load it from a file or something */};

final mapTheme = ThemeReader().read(myTheme);
```
`vector_tile_renderer` is a dependency of this package, so it should just be available.

**Comment by greensopinion** [comment]
thanks for helping out @geisterfurz007
