### ISSUE TITLE
How to use Satellite map

### ISSUE THREAD

**Issue by ARASHz4** [greensopinion/flutter-vector-map-tiles#106]
In map box can use Satellite vector tile i used but only load road and lines

![Screen Shot 2022-12-13 at 4 54 45 PM](https://user-images.githubusercontent.com/10355794/207331692-ad95ad84-bb47-4ad9-a6df-fe7c8b5dc21e.png)

**Comment by greensopinion** [comment]
When I've seen issues like this before, it's usually because there are expressions in the theme that aren't supported by this library.

To troubleshoot the theme, consider adding a logger to the theme, e.g. `ThemeReader(Logger.console()).read(theme)`
