### ISSUE TITLE
Texts should not rotate with map

### ISSUE THREAD

**Issue by ARASHz4** [greensopinion/flutter-vector-map-tiles#107]
Texts in map like country name should not rotate with map

![map v](https://user-images.githubusercontent.com/10355794/208243880-b9bb9912-cb9a-4dff-87b6-e7bfc2d884c5.png)
this is in my app

![Screen Shot 2022-12-17 at 4 49 23 PM](https://user-images.githubusercontent.com/10355794/208243938-d734de95-fcac-4473-8f90-fbc8e9865a75.png)
this is from map box

**Comment by greensopinion** [comment]
Thanks for the issue. You're right, rotation alignment hasn't been implemented.
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-text-rotation-alignment

A good place to start looking if you're interested in improving this library is [symbol_point_renderer.dart](https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/lib/src/features/symbol_point_renderer.dart#L12)

**Comment by greensopinion** [comment]
fixed by 62b81acd8fe2cde32c436037f8161428aceafb09

**Comment by nikosportolos** [comment]
I tried running the example using the latest version and the street names are still rotating along with the map.
I tested all the [suggested providers](https://github.com/greensopinion/flutter-vector-map-tiles#themes-and-tile-providers) and `https://api.maptiler.com/maps/outdoor/style.json`, but none of them seemed to work as expected.

@greensopinion any ideas?

![Screenshot_2023-10-02-12-32-55-262_com example vector_map_tiles_example](https://github.com/greensopinion/flutter-vector-map-tiles/assets/1687886/de208be5-be8f-4bb3-b675-1e75e3660192)
