### ISSUE TITLE
Vector tiles are not repeated horizontally

### ISSUE THREAD

**Issue by geweald** [greensopinion/flutter-vector-map-tiles#110]
Using `flutter_map` raster layers the tiles are repeated left/right when exceeding the -180,180 on low zoom levels (no infinite scroll is possible but the map is repeated as much as the scroll is available), but vector tiles are not. Can this be fixed?

**Comment by greensopinion** [comment]
Yes, this is something that could be improved.

A good place to start looking is [grid_layer.dart](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/grid/grid_layer.dart#L353) and [grid_tile_positioner.dart](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/grid/grid_tile_positioner.dart)

**Comment by greensopinion** [comment]
This issue is addressed in the latest release when using `TileLayerMode.raster` (the default).

Closing, but feel free to reopen if you plan to make a contribution.
