### ISSUE TITLE
Cannot use more than one pbf source

### ISSUE THREAD

**Issue by DanielBerrioB** [greensopinion/flutter-vector-map-tiles#111]
Hello guys, thanks for having this awesome package. It's very helpful!
I'm stumbling with the following issue. It turns out that I need to show some layers for the map, so I'm doing this: 

```
... other children
  VectorTileLayer(
      theme: theme,
      tileProviders: TileProviders({
        'waypoints': NetworkVectorTileProvider(
          urlTemplate:
              'http://$host/data/waypoints/{z}/{x}/{y}.pbf',
          maximumZoom: 14,
        ),
        'aeronav': NetworkVectorTileProvider(
          urlTemplate: 'http://$host/data/aeronav/{z}/{x}/{y}.pbf',
          maximumZoom: 9,
        ),
        'basemap': NetworkVectorTileProvider(
          urlTemplate: 'http://$host/data/basemap/{z}/{x}/{y}.pbf',
          maximumZoom: 7,
        ),
      }),
    ),
... other children
```

but it seems that each provider is having a background, so it's showing up just the last tile provider (in this case 'basemap'). 
So instead of showing this (which is the result),

<img width="797" alt="Screen Shot 2023-01-12 at 9 16 49 AM" src="https://user-images.githubusercontent.com/34080611/212090016-173d3f6e-6e9b-4c77-923b-13a106bea304.png">

I'm getting this (which is the last tile provider, 'basemap'):

<img width="974" alt="Screen Shot 2023-01-12 at 9 20 57 AM" src="https://user-images.githubusercontent.com/34080611/212091161-001eced6-8fd0-45fe-bd04-bb2266d119c8.png">

So I have found that if I change the order or the providers it always shows the last one. If I do this (place aeronav at the end): 

```
... other children
  VectorTileLayer(
      theme: theme,
      tileProviders: TileProviders({
        'waypoints': NetworkVectorTileProvider(
          urlTemplate:
              'http://$host/data/waypoints/{z}/{x}/{y}.pbf',
          maximumZoom: 14,
        ),
        'basemap': NetworkVectorTileProvider(
          urlTemplate: 'http://$host/data/basemap/{z}/{x}/{y}.pbf',
          maximumZoom: 7,
        ),
        'aeronav': NetworkVectorTileProvider(
          urlTemplate: 'http://$host/data/aeronav/{z}/{x}/{y}.pbf',
          maximumZoom: 9,
        ),
      }),
    ),
... other children
```
I'll get this:

<img width="974" alt="Screen Shot 2023-01-12 at 9 22 54 AM" src="https://user-images.githubusercontent.com/34080611/212091645-64be40e7-49e3-4cc3-9de2-1576334c5a33.png">

So I have one suspicion. Because each tile provider seems to have its own background it's overlapping the previous ones, so the last one is shown. And also I tried putting each provider in its own VectorTileLayer but the same is happening, until I found out that wrapping each VectorTileLayer in an Opacity widget confirms that (see image below):

<img width="911" alt="Screen Shot 2023-01-12 at 9 27 57 AM" src="https://user-images.githubusercontent.com/34080611/212092903-5bcbe00a-726d-42c5-bf1b-962d1fc104d2.png">

```
Opacity(
  opacity: 0.5,
  child: VectorTileLayer(
    theme: theme,
    tileProviders: TileProviders({
      'aeronav': NetworkVectorTileProvider(
        urlTemplate: 'http://$host/data/aeronav/{z}/{x}/{y}.pbf',
        maximumZoom: 9,
      ),
    }),
  ),
),
...other layers
```
Is there any way I can show all the tiles (or layers) together without having that issue? I'll be very grateful if someone can help me. Thanks!

**Comment by DanielBerrioB** [comment]
Hello!
I did another approach. It turns out that one of the layers had a background, so it was hiding the other ones, so what I did was just commented out the background section from the source code and then all the layers were there. After that, I was able to wrap the entire layer in a container and put a custom background. I know it's not the best solution, but in my case, it worked. 
You can check my approach here: https://github.com/DanielBerrioB/dart-vector-tile-renderer (it's a forked version). You can use give it a try.

**Comment by GaelleJoubert** [comment]
Thanks you, I'll have a look :)

On my side, as you can see explain on the issue :  https://github.com/greensopinion/flutter-vector-map-tiles/issues/118 I can't seems to display two sources ...

**Comment by GaelleJoubert** [comment]
Can I ask what theme did you use ? :) I would be curious to have a look at your file if it's a custum one. Thanks you !

**Comment by GaelleJoubert** [comment]
I tryed your approach, but I still have the same issue. 
Only one sources is siplayed (the last one), and I know it doesn't have a background => I can see the color of the scaffold behind (I put a weird color on purpose to see that).
It is so weird, it behave like the data from the second sources wipped out the data from the first one ...

**Comment by DanielBerrioB** [comment]
Hmmm that's really weird. Can I see how you're putting the layers please?

**Comment by GaelleJoubert** [comment]
Yeah it's true, it is super weird !
If you want to have a look at my code, I explain everything in the issue I just opened : https://github.com/greensopinion/flutter-vector-map-tiles/issues/118
If you wanna see anything else, don't hesitate to ask :) thanks you for your help !
