### ISSUE TITLE
Some tiles are not rendering properly from Stadia Maps

### ISSUE THREAD

**Issue by aamirki** [greensopinion/flutter-vector-map-tiles#115]
Hello! Thanks for the great library - I've been working to implement it for the past week or so. I am having an issue where a few tiles at different zoom levels never get rendered properly when I have the tile provider set from Stadia Maps. It is also the same tiles each time that don't render properly. This happens both with the built in `lightTheme()` as well as a custom theme. I've included some screenshots to show what I mean, no roads or labels appear.

Here is a reduced version of what my code looks like:
```
class MapExample extends StatelessWidget {

  MapExample();

  VectorTileProvider _tileProvider(String url) {
    return MemoryCacheVectorTileProvider(
      delegate: NetworkVectorTileProvider(
        urlTemplate: url,
        maximumZoom: MapScreenConstants.maxZoom,
      ),
      maxSizeBytes: 1024 * 1024 * 2,
    );
  }

  String _stadiaURL() {
    var apiKey = dotenv.env['STADIA_MAPS_API_KEY'];
    return 'https://tiles.stadiamaps.com/data/openmaptiles/{z}/{x}/{y}.pbf?api_key=$apiKey';
  }

  @override
  Widget build(BuildContext context) {
    var providers = <String, VectorTileProvider>{
      'openmaptiles': _tileProvider(_stadiaURL()),
    };
    return FlutterMap(
      options: MapOptions(
        interactiveFlags: InteractiveFlag.drag |
            InteractiveFlag.flingAnimation |
            InteractiveFlag.pinchMove |
            InteractiveFlag.pinchZoom |
            InteractiveFlag.doubleTapZoom,
        center: LatLng(42.3925102, -71.1025718),
        zoom: 12,
        keepAlive: true,
      ),
      children: [
        VectorTileLayer(
          tileProviders: TileProviders(providers),
          theme: renderer.ProvidedThemes.lightTheme(),
          showTileDebugInfo: true,
        ),
      ],
    );
  }
}
```

and the relevant parts of my pubspec.yaml file:
```
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ^3.3.10

dependencies:
  flutter_map: 3.1.0
  vector_map_tiles: 3.1.4
  vector_tile_renderer: 3.0.4
```

I also turned on the theme logger before and saw this get logged, not sure if it's relevant to the issue:
```
flutter: WARN: theme layer type raster not implemented
```

Any ideas what could be going on here? I have switched out the theme provider to Mapbox and it seemed to not have this issue. Some more info is that I tested this on Android and it worked fine, this only happens for me on iOS

Screenshots:
![image](https://user-images.githubusercontent.com/32246677/213310184-589b0a95-f397-455a-9026-54353ddcdced.png)
![image](https://user-images.githubusercontent.com/32246677/213310200-07673195-04dd-4605-9f94-dbd242ba8c20.png)

**Comment by ianthetechie** [comment]
One more datapoint is that I have attempted to reproduce this with a minimal application and it doesn't seem to be an issue there. That's a bit surprising as I'd expect it to be consistent given the same inputs.

I also talked to the OP and it doesn't seem to occur on his Android device; only his iPhone (I was unable to reproduce on my iPhone). I'll try to post some more details with a minimal example later if that would help.

**Comment by greensopinion** [comment]
From the screenshot it looks like the bad tiles aren't rendering at all. This library renders tiles twice: one at a lower zoom level with less detail, then again with higher detail layered over top. So the tiles that  appear to be rendering incorrectly are in fact not rendered, it's just the background tile showing through.

When I've seen this before it's been due to a corrupted version of the tile in the on-disk cache. Clearing the cache solved the issue for me. 

Are there any stack traces or errors emitted to the console? It would be helpful if you could post them here to help troubleshoot.

**Comment by aamirki** [comment]
No errors in the console when I was debugging this (besides the `flutter: WARN: theme layer type raster not implemented`). I will try clearing the cache though!

**Comment by ianthetechie** [comment]
Oh huh, cache could definitely do it, and would explain the reason it isn't reproducible across nearly identical apps or tile providers. Next question is how/why a tile got corrupted in disk cache :thinking:

**Comment by aamirki** [comment]
This works now that I have deleted the cache - thank you for the help!
