### ISSUE TITLE
Hillshade with raster-dem

### ISSUE THREAD

**Issue by harsh24** [greensopinion/flutter-vector-map-tiles#128]
Does this package support hillshade using raster-dem tiles? @greensopinion

**Comment by greensopinion** [comment]
no, raster-dem is not supported

**Comment by HugoHeneault** [comment]
Hello @greensopinion 

First things first : thank you SO much for all the work put in this vector tiles pub ;)

I'm using MapTiler and I'd like to show hillshades. I found this issue and have two questions : 

1. raster-dem isn't supported but will it be in future? do you have plans/need help for something ?
2. If raster-dem isn't in roadmap, how would you display hillshades on a maptiler vector map ?

Thanks again, have a nice day :)

**Comment by greensopinion** [comment]
Hugo, you're very welcome!

I haven't had a need for raster DEM so far and haven't made any plans to support it. Supporting raster DEM is potentially a lot of effort. If you're interested in looking into it, feel free. It seems like something that would fall within the scope of a vector rendering library. 

Alternatively, you may want to find a tileset that has hillshade represented as a vector layer. This is already supported today, which you can see in the [examples repository](https://github.com/greensopinion/flutter-vector-map-tiles-examples) - both Thunderforest and Mapbox Outdoor themes use this approach.
