### ISSUE TITLE
Text scaling at different zoom levels

### ISSUE THREAD

**Issue by moneytoo** [greensopinion/flutter-vector-map-tiles#133]
Hello there. I tried couple of maps and styles - OSM planet converted using Planetiler as well as MapLibre [demo tiles](https://maplibre.org/maplibre-gl-js-docs/api/). When I zoom the map, text scales with the map (within some ranges - zoom levels I presume). The most noticeable difference is for example at zoom levels like 5.49 vs 5.50:

<img width="509" alt="vector_map" src="https://user-images.githubusercontent.com/1071643/229046261-c95611b6-e1c8-4f4b-a7c1-fb5e85742c55.png">

In MapLibre GL JS, the text retain its size during zoom. To provide the best readable and accessible map to users, I would expect the text to stay the same size.

**Comment by greensopinion** [comment]
Can you confirm which version of this library you're using? If you're using 3.3.x, you may want to try `TileLayerMode.vector` which should address the issue. More details in the [upgrading guide](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/UPGRADING.md#from-32x-to-330)

**Comment by moneytoo** [comment]
I was using 3.3.2. This option indeed resolves the issue. Thank you kindly.
