### ISSUE TITLE
Dashed lines do not render dashed

### ISSUE THREAD

**Issue by moneytoo** [greensopinion/flutter-vector-map-tiles#134]
When creating a style from scratch in Maputnik as well as trying other existing styles, dashed lines (`line-dasharray`) do not render.

```json
{
  "id": "boundary_3",
  "type": "line",
  "source": "openmaptiles",
  "source-layer": "boundary",
  "minzoom": 8,
  "filter": [
    "all",
    ["in", "admin_level", 3, 4]
  ],
  "layout": {"line-join": "round"},
  "paint": {
    "line-color": "#9e9cab",
    "line-dasharray": [5, 1],
    "line-width": {
      "base": 1,
      "stops": [
        [4, 0.4],
        [5, 1],
        [12, 1.8]
      ]
    }
  }
}
```

Flutter:
![image](https://user-images.githubusercontent.com/1071643/229112934-9a23cf30-ed24-4ab9-bd09-017442d0dbdd.png)

Maputnik:
![image](https://user-images.githubusercontent.com/1071643/229113010-a6585f02-1680-4cda-a9b4-347d48a7f84f.png)

**Comment by greensopinion** [comment]
I'm not having a problem with dashed lines, likely there's an issue with the library interpreting your theme:

![Simulator Screen Shot - iPhone 14 - 2023-04-05 at 08 22 17](https://user-images.githubusercontent.com/18102398/230127847-4d8b62fb-3d28-4c68-8d3e-945de43b9bb9.png)

Here's the style for those lines:

```
        {
          "id": "path_pedestrian",
          "type": "line",
          "source": "openmaptiles",
          "source-layer": "transportation",
          "minzoom": 15.000000001,
          "maxzoom": 18,
          "filter": [
            "all",
            ["==", "\$type", "LineString"],
            ["!in", "brunnel", "bridge"],
            ["in", "class", "pedestrian", "path"]
          ],
          "paint": {
            "line-color": "#ffffff",
            "line-dasharray": [1, 0.7],
            "line-width": {
              "base": 1.2,
              "stops": [
                [14, 0.5],
                [20, 10]
              ]
            }
          }
        }
```

you can try it out here: https://github.com/greensopinion/flutter-vector-map-tiles-examples

**Comment by moneytoo** [comment]
Thanks for your confirmation. I'm able to get dashed lines when editing the style used in the example so I should be able to find out why.
