### ISSUE TITLE
[Bug] Delay in showing text when map is rotating

### ISSUE THREAD

**Issue by sikandernoori** [greensopinion/flutter-vector-map-tiles#135]
There is a significant delay of showing text when map is rotated or Zoomed In/out or moved.

Seems like a Bug, but from code based it seems like a workaround was done to remove jitter.

Do we have plan on fixing it ?

https://user-images.githubusercontent.com/16399272/229510063-3e555ebe-3e64-4e9a-8713-2d16a223736f.mov

**Comment by greensopinion** [comment]
Delayed text rendering while zooming is by design, since without it the frame rate drops significantly and causes jank. There is no plan to address this issue, since it's a limitation of the underlying Flutter framework. You may want to get on #120 since there is some related discussion there.

**Comment by greensopinion** [comment]
Great! I look forward to seeing what you come up with. It would be awesome to have the jank issue fixed.
