### ISSUE TITLE
Vector tile without background.

### ISSUE THREAD

**Issue by Duoquote** [greensopinion/flutter-vector-map-tiles#14]
I would like to display a vector tile map, which displays some polygons and I need to display them on top of other layers because. If it was just a tilelayeroptions object, I could pass a background color argument and make it transparent. Is there any way to make it like that in vector tiles too?

![image](https://user-images.githubusercontent.com/16341937/134628455-aba12c6e-ba7c-4039-a2c7-4fef29476019.png)

**Comment by greensopinion** [comment]
Hi,

The background in vector tiles comes from the theme, in this case here: https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/lib/src/themes/light_theme.dart#L97
By providing a theme without a background, you should get the effect that you're looking for.

David

**Comment by GaelleJoubert** [comment]
I have the same issue, even after deleting the background in the theme, still impossible to remove it !
