### ISSUE TITLE
PMTILES support?

### ISSUE THREAD

**Issue by mweller83** [greensopinion/flutter-vector-map-tiles#140]
Do you have any plans to add support for PMTILES (https://github.com/protomaps/PMTiles)?
AFAIK it would „just“ mean to load the vector tiles in a different manner and I would also be interested to add a implementation for that myself — if you‘re interested.

**Comment by greensopinion** [comment]
@mweller83 no plans at the moment. Thanks for offering! 

I'm not sure what it would look like, but you might want to start by implementing a [VectorTileProvider](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/vector_tile_provider.dart#L10).
One thing to consider is whether PMTILES support could/should be added in this repository or as a separate repository.

**Comment by greensopinion** [comment]
closing for now, feel free to reopen if there's interest in working on this
