### ISSUE TITLE
Add option to configure storage cache location

### ISSUE THREAD

**Issue by JulianBissekkou** [greensopinion/flutter-vector-map-tiles#146]
It would be nice if I am able to give my users the ability to delete the map caches and free up additional space if needed.
This is currently not possible because the internally created `ByteStorage` is hardcoded to use the `${getTemporaryDirectory()}/.vector_map`.

I would be nice if the cache itself or the url would be expose so we can make sure that we are able to delete the data.

**Comment by greensopinion** [comment]
> I would be nice if the cache itself or the url would be expose so we can make sure that we are able to delete the data.

Would you prefer to have an API to do that?
What is the use-case for deleting the cache?

**Comment by JulianBissekkou** [comment]
In my app the user should be able to save disk space by deleting the map cache. In the settings there is a button where the user is able to do that.
If we change the map we would like to keep this option.
