### ISSUE TITLE
Widget support

### ISSUE THREAD

**Issue by stolus902** [greensopinion/flutter-vector-map-tiles#15]
Hi, is there a plan to support not only layer `VectorTileLayerOptions` but also to have a `VectorTileLayerWidget` that will accept options, same as every other layer has in the `flutter_map`?
This will help a lot with building custom map abstractions

**Comment by greensopinion** [comment]
Hi, I'm not sure what you're asking for. Can you provide an example of what
you mean? e.g. a code sample? It would also help to understand the
motivation for this question - i.e. what is your use-case?

**Comment by stolus902** [comment]
@greensopinion Hi, I mean to use vector tiles as a Widget, not only as Layer options, so `FlutterMap` has both `layers` and `children` property and I can eg. use `TileLayerWidget` in children or `TileLayerOptions` in layers and both behave the same way (because widget only accepts options). My use case is to build custom map abstraction when I can place markers, widgets, and stack it properly, and using `children` gives that flexibility. So I'd be very nice to have `VectorTileLayerWidget` that I can use in the widget tree, not only in `layers`. Can you support that?

**Comment by greensopinion** [comment]
Hi,

I have no plans at the moment to support the vector tile layer as a widget.
It's not clear to me why you'd need to do that, since you can stack widgets
in FlutterMap using layers too. Feel free to provide more detail, or a code
sample (e.g. as a fork) - if it's relatively straightforward and the
use-case makes sense, then I might consider it.

David

**Comment by Wackymax** [comment]
Hi,

I am in the same situation as @stolus902 . All of my other layers are rendered as map children which is the new recommended way of handling layers in flutter_map, but map children are rendered beneath the old layers. Changing this should be fairly easy by adding a new file with the following contents and exposing it for public use.

`
class VectorTileLayerWidget extends StatelessWidget {
  final VectorTileLayerOptions options;

  const VectorTileLayerWidget({Key? key, required this.options})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    final mapState = MapState.maybeOf(context)!;
    return VectorTileLayer(options, mapState, mapState.onMoved);
  }
}
`

**Comment by greensopinion** [comment]
Added widget-based layer, in version 1.0.22 https://pub.dev/packages/vector_map_tiles
