### ISSUE TITLE
Upgrade flutter_map v4

### ISSUE THREAD

**Issue by HugoHeneault** [greensopinion/flutter-vector-map-tiles#150]
Hello, 

flutter_map just got it's v4. https://pub.dev/packages/flutter_map/changelog

Could you update your dep so it works with it?

I hope their new TileLayer implem won't make it tough to migrate 🤞

Thanks :)

**Comment by HugoHeneault** [comment]
Just saw https://github.com/greensopinion/flutter-vector-map-tiles/pull/136, will try it :)

**Comment by greensopinion** [comment]
this is now merged
