### ISSUE TITLE
placeholder tile color

### ISSUE THREAD

**Issue by mikael-epigram** [greensopinion/flutter-vector-map-tiles#154]
While tiles are being fetched the canvas has a somewhat grey color by default as in [this issue](https://github.com/fleaflet/flutter_map/issues/35). Is the color customizable in vector map tiles as well?

**Comment by greensopinion** [comment]
when using `TileLayerMode.vector` tiles that are not loaded are not displayed at all, so the colour of the parent widget to the map will show through

**Comment by mikael-epigram** [comment]
What about for `TileLayerMode.raster`?
