### ISSUE TITLE
Not Compatible With http v1.0.0 

### ISSUE THREAD

**Issue by ARASHz4** [greensopinion/flutter-vector-map-tiles#155]
`Because every version of vector_map_tiles depends on http ^0.13.3 and app depends on http ^1.0.0, vector_map_tiles is forbidden.
So, because app depends on vector_map_tiles ^4.0.0, version solving failed.`

**Comment by greensopinion** [comment]
Thanks for the issue. Is this blocking you?

**Comment by ARASHz4** [comment]
> Thanks for the issue. Is this blocking you?

Yes i can't update depends and some libraries use http 1.0.0

**Comment by greensopinion** [comment]
addressed on #158
