### ISSUE TITLE
Not compatible with flutter_map v5.0.0 

### ISSUE THREAD

**Issue by ARASHz4** [greensopinion/flutter-vector-map-tiles#162]
Not compatible with flutter_map v5.0.0

`Because vector_map_tiles 4.0.0 depends on flutter_map ^4.0.0 and no versions of vector_map_tiles match >4.0.0 <5.0.0, vector_map_tiles ^4.0.0 requires flutter_map ^4.0.0.
So, because app depends on both flutter_map ^5.0.0 and vector_map_tiles ^4.0.0, version solving failed.`

**Comment by mvarendorff** [comment]
This already has a PR here: #158

**Comment by greensopinion** [comment]
thanks for the issue, fixed with #158
