### ISSUE TITLE
StyleReader fails on public style

### ISSUE THREAD

**Issue by dfrobese** [greensopinion/flutter-vector-map-tiles#165]
Hi,
I use the openAPI style "https://api.tiles.openaip.net/api/styles/openaip-default-style.json" to read the style of the map. the call fails with the error message "message":"Not Authorized - No Token".
The style is open and needs no token, but internal in your code the sourcePath  "https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v8.json?secure& " of the given style is called and this needs a token. 

My question is, how I can pass my mapbox token with your api. Or is ther any workaround to avoid this erro?

Thanks,

Dirk

**Comment by greensopinion** [comment]
Examples of passing a token are provided here: https://github.com/greensopinion/flutter-vector-map-tiles-examples
