### ISSUE TITLE
WARN: theme layer type hillshade not implemented

### ISSUE THREAD

**Issue by koenhagen** [greensopinion/flutter-vector-map-tiles#167]
Add support for hillshade theme layers.

This error shows up when using a maptiler map with hillshade using the default project in the example folder

**Comment by greensopinion** [comment]
Thanks for the issue. 

> Add support for hillshade theme layers.

I'm not sure what's involved, but I have no plans to do that. Feel free to look into it.

You'll find several examples of hillshade (not the layer, but the effect) here: https://github.com/greensopinion/flutter-vector-map-tiles-examples

**Comment by greensopinion** [comment]
closing for now
