### ISSUE TITLE
I can't display my local Mbtiles files Carte.Mbtiles 

### ISSUE THREAD

**Issue by scorpiomac** [greensopinion/flutter-vector-map-tiles#171]
I cloned the basic git repository.
I've added my map in assets/map/map.mbtiles
In main.dart I changed the tiles path to assets/carte/carte.mbtiles but when I run, I still have the map of Japan displayed.
Thanks in advance for your help

**Comment by greensopinion** [comment]
mbtiles isn't supported directly by this library, but others have made progress. You may want to take a look at #170
