### ISSUE TITLE
Update flutter_map dependency to 6.1.x

### ISSUE THREAD

**Issue by JaffaKetchup** [greensopinion/flutter-vector-map-tiles#175]
The next version of flutter_map is coming soon, with breaking changes for all users and plugins!

Expected CHANGELOG: https://github.com/fleaflet/flutter_map/blob/release-prep/CHANGELOG.md
Likely to be merged PR with significant impacts: fleaflet/flutter_map#1615
Release prep PR: fleaflet/flutter_map#1632
New documentation (path liable to change): https://docs.fleaflet.dev/v/v6-1
Expected migration instructions, suitable for most users: https://docs.fleaflet.dev/v/v6-1/getting-started/migrating-to-v6
List of commits since v5 (more to come): https://github.com/fleaflet/flutter_map/compare/v5.0.0...master

**Comment by greensopinion** [comment]
Thanks for the heads-up @JaffaKetchup 

All, we have 4 pull requests to get to 6.0:  #169 #177 #182 #184
I have limited time to get this in. It would be really helpful if you could all coordinate, agree on and review a single PR.

**Comment by JaffaKetchup** [comment]
Just to note, v6.1.0 is now available. @greensopinion I'm happy to try to review one of the PRs, just possibly won't have time today.

**Comment by greensopinion** [comment]
Thanks Luke!

**Comment by greensopinion** [comment]
new version published, see example [commit to upgrade](https://github.com/greensopinion/flutter-vector-map-tiles-examples/commit/203098f2a0445e5d802157506cd1af36e3153e42)
