### ISSUE TITLE
Package available for web?

### ISSUE THREAD

**Issue by Henk-Keijzer** [greensopinion/flutter-vector-map-tiles#191]
Are there any plans to make the package available for web? I saw that the package depends on patr_provider, which is not available for web either.... butt nevetheless, an implementation for web would be much appreciated.

**Comment by thunderbug1** [comment]
I think there are still performance issues holding that back https://github.com/greensopinion/flutter-vector-map-tiles/issues/64 
but yeah, web support would be amazing.

**Comment by greensopinion** [comment]
web support is not planned, since performance is not good enough (#64)
