### ISSUE TITLE
Raster Tiles Usage

### ISSUE THREAD

**Issue by mehmetkalayci** [greensopinion/flutter-vector-map-tiles#192]
Hello,

Can I use the library for .mbtiles file which consists of png files?

Thank you

**Comment by greensopinion** [comment]
Hi, this library is only for vector tiles. If you mbtiles are in vector format, then yes you could do that - see #170.

Alternatively if you have raster images in mbtiles, this could be a good place to start: https://github.com/DonWasyl/flutter_map_mbtiles_provider

**Comment by mehmetkalayci** [comment]
Thank you for reply.
I have already opened an issue in the repo that you suggested.
I made an mbtiles file which consists of png files. I use the plugin and did some debugging. I am getting correct sql queries and data. Unfortunately, all I see is blank screen, insted of seeing the tiles.
Please can you check https://github.com/DonWasyl/flutter_map_mbtiles_provider/issues/3#issuecomment-1889976274
