### ISSUE TITLE
would something like https://github.com/fleaflet/flutter_map_cancellable_tile_provider help in performance

### ISSUE THREAD

**Issue by celron** [greensopinion/flutter-vector-map-tiles#194]
In using the this vector package, I noticed multiple requests for the same tiles.  The package mentioned was to cancel multiple calls for the same tiles that are not needed and I was wondering if a package like this could help flutter_vector_map_tiles.

**Comment by greensopinion** [comment]
thanks for the tip @celron, added https://github.com/greensopinion/flutter-vector-map-tiles/commit/4883ef7b4fcbea2552f829511d7357c9df8a989a
