### ISSUE TITLE
Override background color of VectorTileLayer

### ISSUE THREAD

**Issue by tobesucht** [greensopinion/flutter-vector-map-tiles#197]
Hi, 

thanks a lot for this great project!
I am using a standard theme from MapBox together with the VectorTileLayer. The theme is having a white background before the tiles are loaded. Is there any chance to override the white color with a different one or do I have to create a custom MapBox style for this?

Thanks

**Comment by greensopinion** [comment]
Are you looking for this? 

https://pub.dev/documentation/flutter_map/latest/flutter_map/MapOptions/backgroundColor.html

Alternatively you can change the style to have a different background color.
