### ISSUE TITLE
Google maps support - Issue

### ISSUE THREAD

**Issue by MathavK-raptee** [greensopinion/flutter-vector-map-tiles#201]
There are understanding problems in code, Im trying to implement google maps, It fetches style json, Im not sure google maps is having api that can provide style json. Also the documentation contains only usage for maps like stadia, maptiler etc. Can you help me to use google vector tiles combining with vector_tile_maps?

**Comment by greensopinion** [comment]
There are multiple vector tile APIs available, see [the readme for some examples](https://github.com/greensopinion/flutter-vector-map-tiles?tab=readme-ov-file#more-examples)

Google maps provides docs on their APIs, eg. https://developers.google.com/maps/documentation/tile

**Comment by MathavK-raptee** [comment]
I have tried using the same earlier but your package also requires style of the map as style.json. Which is not found in google API's. I think it's not possible to apply google maps to your package.
