### ISSUE TITLE
not render fill-pattern ???

### ISSUE THREAD

**Issue by anhtu812** [greensopinion/flutter-vector-map-tiles#214]
![Screenshot from 2024-09-23 13-17-06](https://github.com/user-attachments/assets/ad26e47c-4d0c-427b-b843-295d857cc0cd)

plugin not render fill-pattern from sprite ???
I show on web, it ok.
If use vector_map_tiles plugin, it show black color

**Comment by greensopinion** [comment]
fill-pattern is not implemented

feel free to submit a PR against https://github.com/greensopinion/dart-vector-tile-renderer
