### ISSUE TITLE
Unable to Zoom Beyond Level 18 Using flutter-vector-map-tiles with MapTiler

### ISSUE THREAD

**Issue by EnuS317** [greensopinion/flutter-vector-map-tiles#221]
I am using the `flutter-vector-map-tiles` package with [MapTiler](https://www.maptiler.com/) as the map data provider. I understand that MapTiler provides zoom level data only up to level 14. However, when I try to zoom further than level 18, nothing is drawn on the map. I would like to enable zooming up to level 20. 

Is there a way to upscale or re-use MapTiler's data to enable zooming up to level 20? I saw that overzoom is supported https://github.com/greensopinion/flutter-vector-map-tiles/pull/68

Thank you!

**Comment by greensopinion** [comment]
The [flutter-vector-map-tiles-examples](https://github.com/greensopinion/flutter-vector-map-tiles-examples) project shows using MapTiler with maximum zoom up to 22.

Maximum zoom in the example is set here: https://github.com/greensopinion/flutter-vector-map-tiles-examples/blob/c0ce67ee76fe504d4457145243c14ed80b288171/lib/map.dart#L36
