### ISSUE TITLE
Can't render Mapbox tiles

### ISSUE THREAD

**Issue by tmemm** [greensopinion/flutter-vector-map-tiles#23]
Hi, I've been playing around with this plugin for the last few days (and am really excited about it!), but I had a question around Mapbox support. With the given example, I'm able to successfully render a map with the Stadia Maps URL. However, when I try to use the Mapbox URL, it doesn't seem to render the tiles. I don't see any errors to the console. I was wondering if this is a known issue and/or if anyone has have any ideas to fix this.

Repro steps:
1. Download the example.
2. Add your Stadia Maps access token to the Stadia Maps URL in main.dart.
3. Change the zoom level to 15 (so that we should see streets and names on the initial render).
3. Run the application. I've encountered this issue on both Mac and Android (the only platforms I've tried).
4. See that it renders the map correctly.

![Screen Shot 2022-01-07 at 11 07 09 AM](https://user-images.githubusercontent.com/97302858/148572942-07979afb-88dc-40f9-bf4d-1e90c226423f.png)

5. Close the application and **clear the cache**. On Android, I'm doing this by long pressing on the app icon and navigating to "clear storage." On Mac, I'm doing this by deleting the "example" folder at ~/Library/Containers/.
6. Comment out the Stadia Maps URL, uncomment the Mapbox URL, and add your access token.
7. Run the application again.
8. See that streets/names don't show up.

![Screen Shot 2022-01-07 at 11 11 23 AM](https://user-images.githubusercontent.com/97302858/148572943-0a2f88e0-ecc3-4542-9092-d6c8843c07e9.png)

**Comment by greensopinion** [comment]
Hi, thanks for the issue. I've seen this problem too, here's what I've found:

Though vector tiles have the same data structure and format, they don't necessarily have the same conventions when it comes to naming of source layers, and values for attributes. The theme that you use selects the data to render -- but if the data doesn't match the expected values as specified in the theme, then those features won't render. You can see the same result in https://maputnik.github.io/ by selecting the OSM Liberty style then setting the data source to Mapbox.

To use Mapbox you'll need to supply a style that works with Mapbox tilesets. A good place to start looking at Mapbox styles is their [Gallery](https://www.mapbox.com/gallery/). 

Once you've selected a style you'll find that some of the features used in the style aren't implemented in this library. For example, I had troubles with the background color function in one theme, and the `text-placement` function. For incompatibilities like this usually you'll see a stack trace. To solve this problem you can either change the style to use a form that's supported by this library, or you can open an issue for it and consider contributing a pull request.

**Comment by greensopinion** [comment]
closing but feel free to reopen if you think there's a bug here

**Comment by oulianov** [comment]
Hi, thank you for your great work with this plugin and the very useful pointers in your response. 
I'm trying to display a vector Mapbox in my app as well. 
I followed your recommendations. I picked a basic Mapbox theme and tweaked it a bit in https://maputnik.github.io/ to make  `ThemeReader` errors related to `text-anchor` disappear. The theme works in Maputnik.

However, I now have the following warning when reading the theme in Flutter :

```
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [geometry-type], Polygon], [==, [get, class], land]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [geometry-type], LineString], [==, [get, class], land]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [geometry-type], Polygon], [match, [get, type], [runway, taxiway, helipad], true, false]]
I/flutter (13315): WARN: Unsupported expression syntax: [==, [geometry-type], LineString]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], tunnel], [==, [get, class], path], [!=, [get, type], steps], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], tunnel], [==, [get, type], steps], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], tunnel], [==, [get, class], pedestrian], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], tunnel], [step, [zoom], [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, secondary, tertiary, street, street_limited, primary_link, track], true, false], 14, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, street, street_limited, service, track], true, false]], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, class], path], [step, [zoom], [!, [match, [get, type], [steps, sidewalk, crossing], true, false]], 16, [!=, [get, type], steps]], [match, [get, structure], [none, ford], true, false], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, type], steps], [match, [get, structure], [none, ford], true, false], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, class], pedestrian], [match, [get, structure], [none, ford], true, false], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [step, [zoom], [match, [get, class], [motorway, trunk], true, false], 6, [match, [get, class], [motorway, trunk, primary], true, false], 8, [match, [get, class], [motorway, trunk, primary, secondary], true, false], 10, [match, [get, class], [motorway, trunk, primary, secondary, tertiary, motorway_link, trunk_link], true, false], 11, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, secondary, tertiary, street], true, false], 12, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, secondary, tertiary, street, street_limited, primary_link], true, false], 13, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, secondary, tertiary, street, street_limited, primary_link, track], true, false], 14, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, street, street_limited, service, track], true, false]], [match, 
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], bridge], [==, [get, class], path], [==, [geometry-type], LineString], [!=, [get, type], steps]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, type], steps], [==, [get, structure], bridge], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], bridge], [==, [get, class], pedestrian], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], bridge], [step, [zoom], [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, secondary, tertiary, street, street_limited, primary_link, track], true, false], 14, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, street, street_limited, service, track], true, false]], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [==, [get, structure], bridge], [step, [zoom], [match, [get, class], [motorway, trunk], true, false], 13, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, secondary, tertiary, street, street_limited, primary_link, track], true, false], 14, [match, [get, class], [motorway, motorway_link, trunk, trunk_link, primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, street, street_limited, service, track], true, false]], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [zoom], [match, [get, class], [pedestrian], true, false], 15, [match, [get, class], [path, pedestrian], true, false]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [match, [get, class], [canal, river, stream], [match, [get, worldview], [all, US], true, false], [disputed_canal, disputed_river, disputed_stream], [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [match, [get, class], [glacier, landform], [match, [get, worldview], [all, US], true, false], [disputed_glacier, disputed_landform], [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [==, [geometry-type], LineString], [<=, [get, filterrank], 2]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [match, [get, class], [dock, glacier, landform, water_feature, wetland], [match, [get, worldview], [all, US], true, false], [disputed_dock, disputed_glacier, disputed_landform, disputed_water_feature, disputed_wetland], [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [==, [geometry-type], Point], [<=, [get, filterrank], 2]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [match, [get, class], [bay, ocean, reservoir, sea, water], [match, [get, worldview], [all, US], true, false], [disputed_bay, disputed_ocean, disputed_reservoir, disputed_sea, disputed_water], [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [==, [geometry-type], LineString]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [match, [get, class], [bay, ocean, reservoir, sea, water], [match, [get, worldview], [all, US], true, false], [disputed_bay, disputed_ocean, disputed_reservoir, disputed_sea, disputed_water], [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [==, [geometry-type], Point]]
I/flutter (13315): WARN: Unsupported expression syntax: [<=, [get, filterrank], [+, [step, [zoom], 0, 16, 1, 17, 2], 2]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, sizerank], 18, 9, 12]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, sizerank], [coalesce, [get, name_en], [get, name]], 15, [get, ref]]
I/flutter (13315): WARN: Unsupported expression syntax: [interpolate, [cubic-bezier, 0.5, 0, 1, 1], [zoom], 11, [match, [get, type], suburb, 11, 10.5], 15, [match, [get, type], suburb, 15, 14]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [<=, [get, filterrank], 3], [match, [get, class], settlement, [match, [get, worldview], [all, US], true, false], disputed_settlement, [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [step, [zoom], [>, [get, symbolrank], 6], 4, [>=, [get, symbolrank], 7], 6, [>=, [get, symbolrank], 8], 7, [>=, [get, symbolrank], 10], 10, [>=, [get, symbolrank], 11], 11, [>=, [get, symbolrank], 13], 12, [>=, [get, symbolrank], 15]]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 12, 9, 11, 10, 10.5, 12, 9.5, 14, 8.5, 16, 6.5, 17, 4]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 23, 9, 21, 10, 19, 11, 17, 12, 16, 13, 15, 15, 13]
I/flutter (13315): WARN: Unsupported expression syntax: [interpolate, [cubic-bezier, 0.2, 0, 0.9, 1], [zoom], 3, [step, [get, symbolrank], 12, 9, 11, 10, 10.5, 12, 9.5, 14, 8.5, 16, 6.5, 17, 4], 13, [step, [get, symbolrank], 23, 9, 21, 10, 19, 11, 17, 12, 16, 13, 15, 15, 13]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
I/flutter (13315): WARN: Unsupported expression syntax: [all, [<=, [get, filterrank], 3], [match, [get, class], settlement, [match, [get, worldview], [all, US], true, false], disputed_settlement, [all, [==, [get, disputed], true], [match, [get, worldview], [all, US], true, false]], false], [step, [zoom], false, 3, [<=, [get, symbolrank], 6], 4, [<, [get, symbolrank], 7], 6, [<, [get, symbolrank], 8], 7, [<, [get, symbolrank], 10], 10, [<, [get, symbolrank], 11], 11, [<, [get, symbolrank], 13], 12, [<, [get, symbolrank], 15], 13, [>=, [get, symbolrank], 11], 14, [>=, [get, symbolrank], 15]]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 13, 6, 12]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 16, 6, 15, 7, 14]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 18, 9, 17, 10, 15]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 23, 9, 22, 10, 20, 11, 18, 12, 16, 13, 15, 15, 13]
I/flutter (13315): WARN: Unsupported expression syntax: [interpolate, [cubic-bezier, 0.2, 0, 0.9, 1], [zoom], 3, [step, [get, symbolrank], 13, 6, 12], 6, [step, [get, symbolrank], 16, 6, 15, 7, 14], 8, [step, [get, symbolrank], 18, 9, 17, 10, 15], 15, [step, [get, symbolrank], 23, 9, 22, 10, 20, 11, 18, 12, 16, 13, 15, 15, 13]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 10, 6, 9.5, 7, 9]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 21, 6, 16, 7, 13]
I/flutter (13315): WARN: Unsupported expression syntax: [interpolate, [cubic-bezier, 0.85, 0.7, 0.65, 1], [zoom], 4, [step, [get, symbolrank], 10, 6, 9.5, 7, 9], 9, [step, [get, symbolrank], 21, 6, 16, 7, 13]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [zoom], [step, [get, symbolrank], [coalesce, [get, name_en], [get, name]], 5, [coalesce, [get, abbr], [get, name_en], [get, name]]], 5, [coalesce, [get, name_en], [get, name]]]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 11, 4, 9, 5, 8]
I/flutter (13315): WARN: Unsupported expression syntax: [step, [get, symbolrank], 22, 4, 19, 5, 17]
I/flutter (13315): WARN: Unsupported expression syntax: [interpolate, [cubic-bezier, 0.2, 0, 0.7, 1], [zoom], 1, [step, [get, symbolrank], 11, 4, 9, 5, 8], 9, [step, [get, symbolrank], 22, 4, 19, 5, 17]]
I/flutter (13315): WARN: Unsupported expression syntax: [coalesce, [get, name_en], [get, name]]
```
I understand these warnings come from unsupported field values. How would one go about fixing those ?

It would be great if the ThemeReader had some kind of fallback for unsupported values, for example by substituting constants to unsupported expressions. :thinking:

**Comment by mvarendorff** [comment]
Various options:

1) Removing those parts of the theme if not needed (this will also heavily increase performance; in our usecase we could remove a couple dozen unused theme layers like for US highway signs) and FPS jumped from 2-3 to 30.
2) Opening a PR to support those expressions in the [vector-tile-renderer repo](https://github.com/greensopinion/dart-vector-tile-renderer/tree/main/lib/src/themes/expression)
3) Try out my fork of said repo by adding this to your pubspec.yaml
```yaml
dependency_overrides:
  vector_tile_renderer:
    git:
      url: http://github.com/mvarendorff/dart-vector-tile-renderer
      ref: atmina
```

**Comment by greensopinion** [comment]
@oulianov could you attach your theme? I'll have a look.

@mvarendorff thanks for helping out. Feel free to submit PRs with your own improvements!

**Comment by oulianov** [comment]
Thank you @mvarendorff for sharing your ideas. Some layers can be removed, but others less so (e.g. country names). I've looked at your repo but didn't find implementation of said functions. 

@greensopinion Sure thing, here's the theme : https://pastebin.com/S3Ve3gPa

Reading through the [mapbox expression documentation](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#step), here are some details about the unsupported expressions:
- `geometry-type` : filter by type of geometry
- `coalesce`: takes the first non-null value in a list
- `step`: apply a step-wise function to a value
- `cubic-bezier`: [non-linear intepolation](https://pub.dev/packages/bezier)

Do you know what alternative, already implemented expressions could be used? Or how can I go about implementing those? 

I've looked around in the code, but there are many layers of abstraction. For example, even though I know how to do a coalesce in Dart, it's hard for me to know where to start adding this logic in the code. But if you had some pointers about package architecture, or even would be available for an informal chat, I'd love to help you improve this package.

**Comment by greensopinion** [comment]
> Do you know what alternative, already implemented expressions could be used? Or how can I go about implementing those?

A great place to get started is [expression_parser_test.dart](https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/test/src/themes/expression/expression_parser_test.dart) which should have tests for most (all?) supported syntax in expressions.

**Comment by greensopinion** [comment]
@oulianov here's an example PR adding support for `geometry-type` [dart-vector-tile-renderer/pull/14](https://github.com/greensopinion/dart-vector-tile-renderer/pull/14)

Feel free to comment on it or create some PRs of your own!

**Comment by ch-muhammad-adil** [comment]
@greensopinion Hello, 
I am facing almost similar problems with street map. I just want to use basic Street map theme of mapbox. But mostly areas are not loading for me. 

I have tried to use Stadia but where ever i go it is always ignoring 1 tile. 

Is there any chance that i need to clear cache or delete the app to make stadia functional?

**Comment by greensopinion** [comment]
Muhammad, if you want to use Mapbox you should be able to. I've tried several of their themes and they work well. You can [see the results in the gallery](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/gallery/gallery.md) and you'll find an example showing Mapbox themes working on [the mapbox-example branc](https://github.com/greensopinion/flutter-vector-map-tiles/tree/mapbox-example).

If you have one tile that's not showing correctly with Stadia, there's a good chance that there is some bad data in the cache. Clearing the cache may fix the issue. At the moment there is no good way to do that other than figuring out where the cache is located and deleting the files. Alternatively you could change "openmaptiles" to something else [here](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/example/lib/main.dart#L67) but if you do that you'll also need to change the source to match in the theme. 

If you have a stack trace on the application console, please open an issue because it will help me to understand what happened. Perhaps there's something that we could do to prevent blank tiles.

**Comment by ch-muhammad-adil** [comment]
Hello @greensopinion , thank you for reply. I have tried that example from [here](https://github.com/greensopinion/flutter-vector-map-tiles/blob/mapbox-example/example/lib/model.dart) but unfortunately my map is entirely not loading. I have downloaded whole theme from the mentioned URL and saved as a const String then encoded 

`mapboxTheme = vt.ThemeReader().read(mapBoxThemeEncoded);`

<img width="438" alt="Screenshot 2022-07-19 at 8 55 13 PM" src="https://user-images.githubusercontent.com/8264639/179795092-5df385f0-6540-45a4-ac0d-b050a9bea30f.png">

**Comment by ch-muhammad-adil** [comment]
as soon as i switch back to 

`theme: vt.ProvidedThemes.lightTheme(),`

I see 

<img width="438" alt="Screenshot 2022-07-19 at 9 08 14 PM" src="https://user-images.githubusercontent.com/8264639/179797849-e2012cc8-0316-49fb-b4dd-779b548fa469.png">

**Comment by ch-muhammad-adil** [comment]
Do i need to first load the map and then load the theme?

**Comment by greensopinion** [comment]
Looks like this is a case of "works for me" with the [mapbox example](https://github.com/greensopinion/flutter-vector-map-tiles/tree/mapbox-example)

Here's what I did:

1. cloned this repository to get a clean local copy `git clone git@github.com:greensopinion/flutter-vector-map-tiles.git && cd  flutter-vector-map-tiles`
2. `git checkout mapbox-example`
3. `git reset --hard 9068ae5` (just to be sure)
4. created a file `example/lib/api_key.dart` with contents `const mapboxApiKey = '<my-mapbox-key>';`
5. `cd example`
6. `flutter pub get`
7.  `flutter run --debug`

If that's not working for you, it would be great if you could post any console messages (e.g. stack traces, errors) here.

![Screen Shot 2022-07-19 at 5 34 46 PM](https://user-images.githubusercontent.com/18102398/179870926-d461b619-0ab6-4d46-b5b7-ae17874b2c8c.png)

**Comment by greensopinion** [comment]
I've added some examples that you may find helpful here: https://github.com/greensopinion/flutter-vector-map-tiles-examples
