### ISSUE TITLE
MBTiles Support

### ISSUE THREAD

**Issue by felixjunghans** [greensopinion/flutter-vector-map-tiles#32]
Hi and thanks for the plugin. Unfortunately I did not find anything in the documentation, but does this plugin also support the use of offline MBTiles?

**Comment by greensopinion** [comment]
Thanks for the issue! Sorry, but MBTiles are not supported.

It would help to understand your use-case. What do you want to achieve with MBTiles?

**Comment by felixjunghans** [comment]
We are currently using MBTiles to provide OSM maps of different regions offline for our users. 

I found the following package [MBTilesImageProvider](https://github.com/DonWasyl/flutter_map_mbtiles_provider). But this is only suitable for MBTiles that contain png data. However, I managed to modify the code so that it now also works with vector maps. If you like I can create a PR for the MBTilesVectorProvider.

**Comment by greensopinion** [comment]
Felix, thanks for the issue. Have you found a solution for MBTiles? If so it would be great if you could share your approach here. I'm not sure if you meant to close this issue.

**Comment by LeeviLeppala** [comment]
> We are currently using MBTiles to provide OSM maps of different regions offline for our users.
> 
> I found the following package [MBTilesImageProvider](https://github.com/DonWasyl/flutter_map_mbtiles_provider). But this is only suitable for MBTiles that contain png data. However, I managed to modify the code so that it now also works with vector maps. If you like I can create a PR for the MBTilesVectorProvider.

Hi @felixjunghans, would you care to shed some light on how you got vector tiles from MBtiles working?

**Comment by mdmm13** [comment]
Hi @felixjunghans - like Leevi, we're also looking into figuring out offline storage for map segments, either via MBTILES or MVT. Which way did you end up going with your offline vector tile solution?

**Comment by goritz** [comment]
Hi, ive had the same issue with loading offline vector tiles from a mbtiles file, and just figured out a working method which i wanted to share:

So, [mbtiles](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) are basically a sqlite database which holds the tiles as gzipped pbf blob data.
You can create your own VectorTileProvider which converts the TileIdentity xyz adress into a SQL Statement like this:
`"SELECT tile_data FROM tiles WHERE zoom_level = ${tile.z} AND tile_column = ${tile.x} AND tile_row = $y"`

As noted in the MBTiles spec, you have to flip the y axis like this:
`int y=(pow(2,z)-1-tile.y).toInt();`
> Note that in the TMS tiling scheme, the Y axis is reversed from the "XYZ" coordinate system commonly used in the URLs to request individual tiles, so the tile commonly referred to as 11/327/791 is inserted as zoom_level 11, tile_column 327, and tile_row 1256, since 1256 is 2^11 - 1 - 791.


Query the mbtiles file and gzip.decode the resulting blob to get the raw pbf vector data

Keep in mind that these pbf tiles are still written to disk by the parent VectorTileProvider (like any network-based provider) and wont be used directly from memory

**Comment by mdmm13** [comment]
Thank you so much @goritz for the detailed explanation, much appreciated! We will give it a try these coming weeks and contribute to the source here. 

Stumbled across [this](https://github.com/psytwo1/vector_mbtiles) repo also, where a first stab was made at this approach. Will review and revert back.

Got a feeling that this will be quite the popular feature for this plugin :-)
