### ISSUE TITLE
Add `tileSize` and `zoomOffset` options

### ISSUE THREAD

**Issue by blaugold** [greensopinion/flutter-vector-map-tiles#33]
As described in the [Mapbox docs](https://docs.mapbox.com/help/glossary/zoom-level/#tile-size), their tiles are meant to be rendered at 512x512px. The idea is to reduce network overhead by reducing the number of necessary network requests.

[Leaflet](https://leafletjs.com/examples/quick-start/) supports this by allowing the user to specify two options:
- [`tileSize`](https://leafletjs.com/reference.html#gridlayer-tilesize)
- [`zoomOffset`](https://leafletjs.com/reference.html#tilelayer-zoomoffset)

This issue is related to this https://github.com/greensopinion/flutter-vector-map-tiles/issues/21#issuecomment-1031584292.

**Comment by greensopinion** [comment]
Thanks for the issue. If I understand correctly, Mapbox tiles should already work - but this is needed to use Mapbox as intended.

It would be great if we could address it with a single setting rather than two. Feel free to submit a PR.

**Comment by blaugold** [comment]
Mapbox tiles are drawn correctly in terms of scale already, it's just very inefficient. There is also a misalignment of the details that should be visible at a given integer zoom level, which means that small features are displayed at a zoom level where they are barely visible.

I would prefer a single setting, but I also like Leaflet's approach because it's not specific to one vendor.

**Comment by greensopinion** [comment]
This is a good idea, but I'm not working on it right now. Feel free to submit a PR.

**Comment by greensopinion** [comment]
completed in 1.4.7, see `VectorTileLayerOptions.tileOffset`
