### ISSUE TITLE
Example on hillslade version

### ISSUE THREAD

**Issue by furkan-celik** [greensopinion/flutter-vector-map-tiles#35]
Hi,

I am having some difficulties how to implement hillslade example. I have a custom theme but when I try to use it resulting output is nothing like what is shown in studio.mapbox.com. Can you help me with this? I have set up map like in the example and have a similar url but the result is almost all white.

Thank you

**Comment by greensopinion** [comment]
Hi, thanks for reaching out. If you still want help with this, can you provide an example of what you're trying to do? For example, you could fork this repository and update the example app to show what you're trying to do, then link it here.
