### ISSUE TITLE
Switching between sources

### ISSUE THREAD

**Issue by zegkljan** [greensopinion/flutter-vector-map-tiles#36]
I would like to have switching between an on-line map (pulling from an URL), and an off-line map (pulling from a `mbtiles` file, which does not work yet, but that is beside the point). However, simply providing different tile provider (or even a whole tile layer, see below) does not make the source switch. As suggested in #27, I tried to use different map theme keys for the two sources, but the map is still pulled from the one that was used first.

So this is basically a feature request - allow source switching, or enable clearing the caches or something like that. I can help with a PR, if pointed into the right place and direction.

This is a snipped of my code:

```
if (offlineMapProvider == null)
  VectorTileLayerWidget(
      options: VectorTileLayerOptions(
          tileProviders: TileProviders({
            'online': MemoryCacheVectorTileProvider(
                delegate: NetworkVectorTileProvider(
                    urlTemplate: '... here be template ...',
                    maximumZoom: 14),
                maxSizeBytes: 1024 * 1024 * 5)
          }),
          theme: ThemeReader().read(mapThemeData('online')),
          backgroundTheme: ThemeReader().readAsBackground(
              mapThemeData('online'),
              layerPredicate: defaultBackgroundLayerPredicate)))
else
  VectorTileLayerWidget(
      options: VectorTileLayerOptions(
          tileProviders: TileProviders({
            'offline': MemoryCacheVectorTileProvider(
                delegate: offlineMapProvider!,
                maxSizeBytes: 1024 * 1024 * 5)
          }),
          theme: ThemeReader().read(mapThemeData('offline')),
          backgroundTheme: ThemeReader().readAsBackground(
              mapThemeData('offline'),
              layerPredicate: defaultBackgroundLayerPredicate)))
```
where 'mapThemeData' produces a map theme spec with the argument used as the `source`.

**Comment by zegkljan** [comment]
My bad, I missed the `id` key in the map theme spec. When I change that too, the switching works. However, I still think this is kinda hack/workaround, and that a proper source switching should be possible.

**Comment by greensopinion** [comment]
Jan, thanks for the feature request. I'm glad that you got it working. 

Can you describe how the user experience could be improved over your current solution with a feature specifically designed to support switching sources?

**Comment by zegkljan** [comment]
User experience wouldn't be affected, but it would be less confusing for the developers.

What really threw me off was that not only the tiles are cached, but also the thing that provides the tiles is cached too. I wouldn't be surprised if tiles that were recently used would be reused from the cache, but I was really surprised that the procedure to obtain yet unused tiles is cached too.

Maybe there are reasons why it is the way it is, I did not study the code in depth. If the source switching feature is problematic, maybe providing a warning/info/how-to for such non-intuitive scenarios would help, so that others don't have to waste time learning this too.

**Comment by greensopinion** [comment]
I have no plans to address this. Feel free to submit a PR if you want.
