### ISSUE TITLE
CancellationException occuring with Mapbox vectors

### ISSUE THREAD

**Issue by JosephShering** [greensopinion/flutter-vector-map-tiles#38]
Gave this plugin a try to see if I could get vector maps in my app. Currently a `CancellationException` happens in `tileset_executor_preprocessor.dart` on line 35.

https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/stream/tileset_executor_preprocessor.dart#L35

On line 34 the `deduplicationKey` is `"preprocess: z=8,x=51,y=95"`, if that means anything.

This is my code.

pubspec:
```yaml
flutter_map: ^0.14.0
vector_map_tiles: ^1.4.3
```

```dart
@override
  Widget build(BuildContext context) {
    return FlutterMap(
        options: MapOptions(
            center: LatLng(40.632714, -106.481879),
            zoom: 9.0,
            rotationThreshold: 0,
            maxZoom: 13,
            plugins: [VectorMapTilesPlugin()],
            rotation: 0),
        layers: [
          VectorTileLayerOptions(
            theme: ProvidedThemes.lightTheme(),
            tileProviders: TileProviders({
              'openmaptiles': MemoryCacheVectorTileProvider(
                  delegate: NetworkVectorTileProvider(
                    maximumZoom: 14,
                    urlTemplate:
                        'https://api.mapbox.com/v4/mapbox.light-v10/{z}/{x}/{y}.mvt?access_token=$accessToken',
                  ),
                  maxSizeBytes: 1024 * 1024 * 2)
            }),
          )
        ]);
  }
```

**Comment by greensopinion** [comment]
Tiles need processing before they can be displayed. If the zoom level changes, or if the map is panned such that the tile is no longer needed, then the remainder of any outstanding work is discarded with a `CancellationException`. This saves unnecessary overhead in doing work that is no longer needed. 

Did you notice a problem? i.e. was there a user-visible issue, or undesired behaviour?

**Comment by JulianBissekkou** [comment]
I think users might be confused because some debuggers break on exceptions. AFAIK its fine that the exception is thrown, correct?

**Comment by greensopinion** [comment]
You're right, it could be confusing, especially since it's likely to get picked up by error reporting libraries. Yes, its' fine that the exception is thrown.

**Comment by greensopinion** [comment]
Looks like this could be a case of us [not registering error handlers early enough](https://dart.dev/guides/libraries/futures-error-handling#potential-problem-failing-to-register-error-handlers-early)

ab44c40 has eliminated unhandled `CancellationException` in my testing

It's possible that there could be other code paths that have the same issue, feel free to reopen if you see it again.

**Comment by mikael-epigram** [comment]
I still see CancellationException when swapping between themes on v4.0.0. this is the stack trace:

```
E/flutter ( 8715): #0      QueueExecutor.submit (package:executor_lib/src/queue_executor.dart:25:7)
E/flutter ( 8715): #1      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:97:38)
E/flutter ( 8715): <asynchronous suspension>
E/flutter ( 8715): #2      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41:12)
E/flutter ( 8715): <asynchronous suspension>
E/flutter ( 8715): #3      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64:33)
E/flutter ( 8715): <asynchronous suspension>
E/flutter ( 8715): #4      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34:9)
E/flutter ( 8715): <asynchronous suspension>
```
