### ISSUE TITLE
Unhandled Exception: Cannot retrieve tile: HTTP 204

### ISSUE THREAD

**Issue by zjyhll** [greensopinion/flutter-vector-map-tiles#40]
I can not load this
https://dev-tile.terraqt.com/tile/xyz/{z}/{x}/{y}.pbf?path=cfa08636-3d72-439c-a3be-de686f1ef9e1/cor101/202010/CN-511403/vectortiles

center LatLng(30.253362,103.879004)

maybe it load succeed，but not shown

E/flutter (11409): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Cannot retrieve tile: HTTP 204: https://dev-tile.terraqt.com/tile/xyz/13/6639/3156.pbf 
E/flutter (11409): #0      NetworkVectorTileProvider.provide (package:vector_map_tiles/src/vector_tile_provider.dart:56:7)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409): #1      MemoryCacheVectorTileProvider.provide (package:vector_map_tiles/src/vector_tile_provider.dart:95:15)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409): #2      VectorTileLoadingCache._loadBytes (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:85:15)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409): #3      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:65:15)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409): #4      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:38:12)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409): #5      CachesTileProvider.provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:30:35)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409): #6      VectorTileModel.startLoading.<anonymous closure> (package:vector_map_tiles/src/grid/tile_model.dart)
E/flutter (11409): <asynchronous suspension>
E/flutter (11409):

**Comment by ibrierley** [comment]
A 204 error typically means that there was no content in the response from the http server. Clicking on the url shown, it doesn't seem to return any content, so first place I would look is why isn't the server returning any protobuf / .pbf content.

**Comment by zjyhll** [comment]
> A 204 error typically means that there was no content in the response from the http server. Clicking on the url shown, it doesn't seem to return any content, so first place I would look is why isn't the server returning any protobuf / .pbf content.

https://dev-tile.terraqt.com/tile/xyz/12/3231/1681.pbf?path=8d3dc176-7f8a-4e08-a8c6-08e798deb999/eve1.e/20210517/1ba522c3-4612-4a28-bf78-454bcf67075c/vectortiles

Only some places have data，do I need to modify VectorTileLayerOptions‘s theme

**Comment by greensopinion** [comment]
modifying the theme likely won't help

I think what we need is something like this: https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/cache/vector_tile_loading_cache.dart#L67
Currently if we try to load a tile that's not present, we ignore it by creating an empty tile.

Feel free to submit a PR

**Comment by greensopinion** [comment]
fixed in commit 022580fca9ccf656
