### ISSUE TITLE
What is the ProvidedThemes

### ISSUE THREAD

**Issue by berkayoruc** [greensopinion/flutter-vector-map-tiles#5]
What is the ProvidedThemes and how can I generate or reach ProvidedThemes?

**Comment by greensopinion** [comment]
Hi, you'll find the example shows how to use `ProvidedThemes`, see [main.dart at line 34](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/example/lib/main.dart#L34)

`ProvidedThemes` is a shortcut for `ThemeReader().read(myThemeData);` where `myThemeData` a JSON theme object, e.g. [light_theme.dart](https://github.com/greensopinion/dart-vector-tile-renderer/blob/main/lib/src/themes/light_theme.dart)

**Comment by ch-muhammad-adil** [comment]
Hi there, I still can not get this. I have checked that line and there is nothing useful.

**Comment by greensopinion** [comment]
If you could open a new issue with details of the problem you're having that would be great.
