### ISSUE TITLE
FLUTTER_MAP: Bump version to v1.0.0

### ISSUE THREAD

**Issue by JaffaKetchup** [greensopinion/flutter-vector-map-tiles#57]
Hi there,

'flutter_map' v1.0.0 has just been released with a few breaking changes but many new features, fixes, and performance improvements. Please consider updating your plugin to make it more accessible to users!

If you want to join the new Discord server, either just because, or because you want to offer more support to your users, just join using the link on the README. Please ping me and I'll give you the plugin maintainer role and access to a plugin support channel :)

Many thanks,
'flutter_map' maintainer (Luka S)

**Comment by greensopinion** [comment]
Thanks for the heads-up Luke, and thanks for your work on flutter_map. Updated to flutter_map 1.0.0, bumped version of this library to 2.1.0, and published to [pub.dev](https://pub.dev/packages/vector_map_tiles)
