### ISSUE TITLE
can I select some vector and highlight it？ 

### ISSUE THREAD

**Issue by zjyhll** [greensopinion/flutter-vector-map-tiles#59]
can I select some vector and highlight it？

**Comment by greensopinion** [comment]
This plugin doesn't provide a feature to do that, but there are others (such as poly lines, markers) that do. `flutter_map` enables you to have multiple layers, so you can use this plugin as a base layer with others on top. 

A list of plugins is available here: https://pub.dev/packages/flutter_map#plugins

Some that look like they might be what you're looking for:
* https://pub.dev/packages/flutter_map_line_editor
* https://github.com/OwnWeb/flutter_map_tappable_polyline
