### ISSUE TITLE
WFS?

### ISSUE THREAD

**Issue by barbalex** [greensopinion/flutter-vector-map-tiles#6]
This may be a dumb question due to not understanding vector formats well. But would it be possible to extend this tool to deal with wfs services?

**Comment by greensopinion** [comment]
The great thing about slippy maps is they're layered. [flutter_map](https://github.com/fleaflet/flutter_map) has a plug-in architecture so if you were inclined, you could create a WFS layer that renders over or under a vector map layer.

**Comment by barbalex** [comment]
What I meant is: Aren't WFS layers vector layers too? 
And if so: Could flutter-vector-map-tiles be extended to draw geometries fetched from a WFS service?

**Comment by greensopinion** [comment]
Sounds like you've got some good ideas. I don't know anything about WFS, but it seems plausible. A good place to get started is the [dart-vector-tile-renderer](https://github.com/greensopinion/dart-vector-tile-renderer) library which does the vector tile rendering.

**Comment by barbalex** [comment]
Let's hope someone with the need for this feature and more dart knowledge than me implements this one day, building on dart-vector-tile-renderer.

I might give it a go sometime but I'll probably only make a big mess of it.

**Comment by greensopinion** [comment]
Sounds good! I picked up dart a few months ago - it's fun to learn.
