### ISSUE TITLE
how to get pbf from this url ?

### ISSUE THREAD

**Issue by vrman** [greensopinion/flutter-vector-map-tiles#69]
this is url template i got from my map provider to get pbf :
`https://map.ir/vector/xyz/1.0.0/Shiveh:Vector@EPSG:900913@pbf/13/5268/3224.pbf`

can you help me to convert this url to something that work with your package ?

**Comment by greensopinion** [comment]
it looks like you figured it out!

anyone else needing HTTP headers, see `NetworkVectorTileProvider` which has a `httpHeaders` property
