### ISSUE TITLE
Valid theme for the Vectory Layer 

### ISSUE THREAD

**Issue by paetzold** [greensopinion/flutter-vector-map-tiles#8]
I have issues getting the example running, it looks like 
  
_mapTheme(BuildContext context) {
    // maps are rendered using themes
    // to provide a dark theme do something like this:
    // if (MediaQuery.of(context).platformBrightness == Brightness.dark) return myDarkTheme();
    return ProvidedThemes.lightTheme();
  }

doesn't return a correct Theme, as the code throws this:

[VERBOSE-2:shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: The getter 'id' was called on null.
Receiver: null

Can you give add myDarkTheme() to the example ?

**Comment by greensopinion** [comment]
@paetzold thanks for the issue. Can you provide more detail as to the failure? ie. have you changed the code at all? When I run it from here it works fine so I'd like to understand more about the failure you're experiencing.

If you want a dark theme, you could try [dark-matter-gl-style](https://github.com/openmaptiles/dark-matter-gl-style) or you could make one using [maputnik](https://maputnik.github.io/)
