### ISSUE TITLE
Theme switching

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [greensopinion/flutter-vector-map-tiles#81]
Hi I have this setup, where I am switching a vector map or an orthophoto map with a vector overlay, switching doesn't really work. Everything rendes good when the default value is there. But when I switch, the vector layer doesnt switch the theme and keep loading the theme by the initially loaded theme, while my raster layer turns on off as it should. if I hardcodedly change the initial value everything is good. 

```dart
layers: <LayerOptions>[
        if (widget.isMap)
          VectorTileLayerOptions(
              maximumZoomDifference: 2,
              theme: MapThemes.terrainTheme(),
              tileProviders: TileProviders(
                  {'openmaptiles': _cachingTileProvider(_urlTemplate())})),
        if (!widget.isMap)
          TileLayerOptions(
            opacity: widget.isMap ? 0 : 0.5,
            urlTemplate: "http://localhost:5232/map/{z}/{y}-{x}.jpg",
                        tileProvider: NonCachingNetworkTileProvider(),
          ),
        if (!widget.isMap)
          VectorTileLayerOptions(
              maximumZoomDifference: 2,
              theme: MapThemes.transparentTheme(),
              tileProviders: TileProviders(
                  {'openmaptiles': _cachingTileProvider(_urlTemplate())})),
]
```

**Comment by greensopinion** [comment]
Hi, currently to switch the theme you need to provide a `key` to the map widget that has the theme ID as part of the `key`. This will cause the map to reload whenever the theme changes.

**Comment by TheOnlyBeardedBeast** [comment]
@greensopinion Hi, Thanks it worked correctly!
