### ISSUE TITLE
How to use offline pbf file?

### ISSUE THREAD

**Issue by webasoo** [greensopinion/flutter-vector-map-tiles#85]
Hi, I need use local pbf file as FileTileProvider.
but this plugin support only NetworkVectorTileProvider.
Can it be extend?

**Comment by greensopinion** [comment]
Sure, all you have to do is provide your own implementation of [VectorTileProvider](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/vector_tile_provider.dart#L11)
