### ISSUE TITLE
How can I use OpenstreetMap vector map ?

### ISSUE THREAD

**Issue by Pepslee** [greensopinion/flutter-vector-map-tiles#89]
Is it possible to use https://cloud.maptiler.com/maps/streets-v2/ ?

**Comment by greensopinion** [comment]
I've added support for the missing expressions in [dart-vector-tile-renderer/pull/66](https://github.com/greensopinion/dart-vector-tile-renderer/pull/66)

This is what it looks like with that change:

<img width="1011" alt="Screen Shot 2022-09-13 at 7 56 00 AM" src="https://user-images.githubusercontent.com/18102398/189937461-42d14cd1-b371-425c-8e6b-260391dea7c9.png">

**Comment by greensopinion** [comment]
These improvements are now available with version 3.0.1
