### ISSUE TITLE
Offline Maps as source?

### ISSUE THREAD

**Issue by S-Man42** [greensopinion/flutter-vector-map-tiles#9]
Hi,

great project? Is it planned to use offline sources for the map? Like *.map files or something?

For example: https://www.freizeitkarte-osm.de/android/en/allgemeines.html

Would love to see this :)

**Comment by greensopinion** [comment]
Hi, to use this plug-in with offline maps, you would want to supply a [VectorTileProvider](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/vector_tile_provider.dart#L9) via the [VectorTileLayerOptions](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/options.dart#L21). 
It's not my intention to add that functionality to this project, but it's relatively easily done. For example, the [MemoryCacheVectorTileProvider](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/lib/src/vector_tile_provider.dart#L55) does something similar - but in memory.
