### ISSUE TITLE
[Feature request] Support loading pbf file from local assets

### ISSUE THREAD

**Issue by KristijanZic** [greensopinion/flutter-vector-map-tiles#92]
I imagine a lot of people might want to distribute the vector maps with the app or allow users to download the maps file for usage without the internet connection. Is this something that might be on the roadmap?

**Comment by FaFre** [comment]
I opened a similar issue couple of weeks ago, see this reply in how to implement it: https://github.com/greensopinion/flutter-vector-map-tiles/issues/80#issuecomment-1201519776

Now rethinking it, the implementation will be quite different depending on the use case. It will hard to have a general solution for that I guess.

**Comment by greensopinion** [comment]
Thanks @FaFre you're right, by implementing `VectorTileProvider` you can plug in any kind of map tile source that you want - e.g. over the filesystem, from app assets, from a database, whatever.
