### ISSUE TITLE
Layer above overlay layer not transparent

### ISSUE THREAD

**Issue by psytwo1** [greensopinion/flutter-vector-map-tiles#98]
When I added README's Adding Hillshade to the example, the background of the Hillshade layer was displayed without transparency and the base map layer became invisible.
Is there a setting to make it transparent?

Thank you
![Screen Shot 2022-10-28 at 16 52 39](https://user-images.githubusercontent.com/17922561/198534762-6901eaf1-3e46-4747-a89a-14efa235d5cd.png)

**Comment by greensopinion** [comment]
The example in the readme relies on `fill-opacity` for this purpose. Can you add your theme to this issue so that we can see what you've done?

**Comment by psytwo1** [comment]
What I want to do is to overlay a map showing a specific area on top of the basemap layer.


`
FlutterMap(
  mapController: _mapController,
  children: [
    VectorTileLayer(
        theme: _style(),
        tileProviders: TileProviders({
          'openmaptiles': _cachingTileProvider(_basemapPath()),
          'overlay': _cachingTileProvider(_overlayPath()),
        })
        ),
  ],
),


Map<String, dynamic> _style() {
  return
{
...
    "sources": {
      "openmaptiles": {"type": "vector", "url": "mbtiles://japan.mbtiles"},
      "overlay": {
        "type": "vector",
        "url": "mbtiles://assets/data/tsunami-shinsui.mbtiles"
      }
    },
...
    "layers": [
      {
        "id": "background",
        "type": "background",
        "source": "openmaptiles",
        "paint": {"background-color": "#f8f4f0"}
      },
      {
        "id": "background",
        "type": "background",
        "source": "overlay",
        "paint": {"background-color": "#ffffff", "fill-opacity": 0}
      },
...
basemap style here
...
      {
        "id": "tsunamishinsui",
        "type": "fill",
        "source": "overlay",
        "source-layer": "tsunamishinsui",
        "layout": {"visibility": "visible"},
        "paint": {"fill-color": "#0000FF", "fill-opacity": 0.2}
      }
}
`

Thank you

**Comment by psytwo1** [comment]
I deleted the background of the overlay layer, but the problem that the background is not transparent does not change

Thank you

**Comment by ValorNaram** [comment]
```
{
    "id": "background",
    "type": "background",
    "source": "openmaptiles",
    "paint": { "background-color": "#f8f4f0" }
},
{
    "id": "background",
    "type": "background",
    "source": "overlay",
    "paint": { "background-color": "#ffffff", "fill-opacity": 0 }
}
```

1. Don't use the same `id` twice. Choose another id for the "overlay" layer like `background-overlay`:
```
{
    "id": "background",
    "type": "background",
    "source": "openmaptiles",
    "paint": { "background-color": "#f8f4f0" }
},
{
    "id": "overlay-background",
    "type": "background",
    "source": "overlay",
    "paint": { "background-color": "#ffffff", "fill-opacity": 0 }
}
```
2. If you want to have your overlay background layered over your real background then try the following:
```
{
    "id": "background",
    "type": "background",
    "source": "openmaptiles",
    "paint": { "background-color": "#f8f4f0", "fill-opacity": 1 }
},
{
    "id": "overlay-background",
    "type": "background",
    "source": "overlay",
    "paint": { "background-color": "#ffffff", "fill-opacity": 0. 2 }
}
```

Hope it helps as I am unable to test it

**Comment by ValorNaram** [comment]
> I deleted the background of the overlay layer, but the problem that the background is not transparent does not change

The overlay layer is the one you want to be a bit transparent. You don't want the main layer to have any transparency.

**Comment by psytwo1** [comment]
I tried, but it doesn't work.
I've tried changing some fill-opacity values, but no change.
Isn't fill-opacity being ignored?

Thank you

**Comment by GaelleJoubert** [comment]
I have the same issue for now ...

**Comment by greensopinion** [comment]
I've added some examples here: https://github.com/greensopinion/flutter-vector-map-tiles-examples

The examples don't directly address the issue of using multiple tile sources and transparency, but they do show hillshade.

**Comment by psytwo1** [comment]
I was able to make it work as expected by hacking.
Here is the sample code


```

FlutterMap(
  mapController: _controller,
    options: MapOptions(
      ...
    ),
  children: [
      VectorTileLayer(
        theme: ThemeReader().read(osmBrightJaStyle()),
        tileProviders: TileProviders(
          {
            "openmaptiles": NetworkVectorTileProvider(
                maximumZoom: 14,
                urlTemplate:
                    "https://tiles.stadiamaps.com/data/openmaptiles/{z}/{x}/{y}.pbf?api_key=API_KEY"),
          }  // Doesn't work if multiple TileProviders are specified
        ),
      ),
      VectorTileLayer(
        theme: ThemeReader().read(osmBrightJaStyle()),
        tileProviders: TileProviders({
          'thunderforest_outdoors': NetworkVectorTileProvider(
              maximumZoom: 14,
              urlTemplate:
                  'https://a.tile.thunderforest.com/thunderforest.outdoors-v2/{z}/{x}/{y}.vector.pbf?apikey=API_KEY')
        }),
      ),
  ],
)



Map<String, dynamic> osmBrightJaStyle() {
  return <String, dynamic>{
  ...
    'layers': [
      {
        'id': 'background',
        'type': 'background',
        'source': 'openmaptiles',
        'paint': {
          'background-color': 'rgba(248,244,240,0)',   // set transparency to 0
        } 
      },
      {
        'id': 'landcover-glacier',
        'type': 'fill',
        'metadata': {'mapbox:group': '1444849388993.3071'},
        'source': 'openmaptiles',
        'source-layer': 'landcover',
        'filter': ['==', 'subclass', 'glacier'],
        'layout': {'visibility': 'visible'},
        'paint': {
          'fill-color': '#fff',
          'fill-opacity': {
            'base': 1,
            'stops': [
              [0, 0.9],
              [10, 0.3]
            ]
          }
        }
      },
      ...
      {
        "id": "hillshade_highlight_brightest",
        "type": "fill",
        "source": "thunderforest_outdoors",
        "source-layer": "hillshade",
        "filter": [
          "any",
          [">=", "level", 225]
        ],
        "paint": {"fill-color": "rgba(255,255,255,0.08)"}
      },


```

thank you

**Comment by greensopinion** [comment]
I've provided a multi-layer example: https://github.com/greensopinion/flutter-vector-map-tiles-examples
See https://github.com/greensopinion/flutter-vector-map-tiles-examples/blob/main/lib/examples/multi_layer.dart for details.
